<a href="https://colab.research.google.com/github/6Novabeam/Segmentation_3D/blob/main/Open3D/affichage_open3d_jupyter_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U -q open3d

In [ ]:
!python -c "import open3d as o3d; print(o3d.__version__)"

0.15.2


In [ ]:
import open3d as o3d
from open3d.web_visualizer import draw
import numpy as np
import matplotlib.pyplot as plt

[Open3D INFO] Resetting default logger to print to terminal.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import sys    
path_to_module = '/content/drive/MyDrive/dataset/'
sys.path.append(path_to_module)

### Affichage avec draw / web_visualizer (dans Jupyter Notebook)
- **web_visualizer ou draw** </br>
    o3d.web_visualizer.draw([pcd])</br>
    ou avec draw</br>
    draw([pcd])</br>
- **!ATTENTION! JVisualizer, c'est pour les cameras, NC** </br>
http://www.open3d.org/docs/latest/tutorial/Basic/jupyter.html
- **o3d.visualization.webrtc_server.enable_webrtc()** Ne fonctionne pas, manque le code complet</br>
http://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html

In [ ]:
import open3d as o3d
from open3d.web_visualizer import draw
cube_red = o3d.geometry.TriangleMesh.create_box(1,2,4)
cube_red.compute_vertex_normals()
#cube_red.paint_uniform_color((1.0, 0.0, 0.0))
o3d.web_visualizer.draw(cube_red)

In [ ]:
import open3d as o3d

if __name__ == "__main__":
    print("Load a ply point cloud, print it, and render it")
    sample_ply_data = o3d.data.PLYPointCloud()
    pcd = o3d.io.read_point_cloud(sample_ply_data.path)
    # Flip it, otherwise the pointcloud will be upside down.
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    print(pcd)
    #o3d.visualization.draw([pcd])

    print("Downsample the point cloud with a voxel of 0.05")
    downpcd = pcd.voxel_down_sample(voxel_size=0.05)
    print(downpcd)
    #o3d.visualization.draw([downpcd])
    o3d.web_visualizer.draw([pcd])

### Clustering d'Open3d : 
Open3D-master\examples\python\geometry\point_cloud_dbscan_clustering.py

In [ ]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

if __name__ == "__main__":
    sample_ply_data = o3d.data.PLYPointCloud()
    pcd = o3d.io.read_point_cloud(sample_ply_data.path)
    # Flip it, otherwise the pointcloud will be upside down.
    print("pcd=",pcd)
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])

    with o3d.utility.VerbosityContextManager(
            o3d.utility.VerbosityLevel.Debug) as cm:
        labels = np.array(
            pcd.cluster_dbscan(eps=0.02, min_points=10, print_progress=True))

    max_label = labels.max()
    print(f"point cloud has {max_label + 1} clusters")
    colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
    colors[labels < 0] = 0
    pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])
    #o3d.visualization.draw([pcd])
    #draw([pcd]) #sol 1 
    o3d.web_visualizer.draw([pcd])

pcd= PointCloud with 196133 points.
point cloud has 10 clusters
pcd= PointCloud with 196133 points.


WebVisualizer(window_uid='window_7')

In [ ]:
import open3d as o3d

if __name__ == "__main__":
    print("Load a ply point cloud, print it, and render it")
    sample_ply_data = o3d.data.PLYPointCloud()
    pcd = o3d.io.read_point_cloud(sample_ply_data.path)
    # Flip it, otherwise the pointcloud will be upside down.
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    print(pcd)
    #o3d.visualization.draw([pcd])

    print("Downsample the point cloud with a voxel of 0.05")
    downpcd = pcd.voxel_down_sample(voxel_size=0.05)
    print(downpcd)
    #o3d.visualization.draw([downpcd])
    o3d.web_visualizer.draw([pcd])


Load a ply point cloud, print it, and render it
PointCloud with 196133 points.
Downsample the point cloud with a voxel of 0.05
PointCloud with 4838 points.


WebVisualizer(window_uid='window_8')

### Voxel grid point could : 
Open3D-master\examples\python\geometry\voxel_grid_from_point_cloud.py

In [ ]:
import open3d as o3d
import numpy as np

if __name__ == "__main__":

    N = 2000
    armadillo_data = o3d.data.ArmadilloMesh()
    pcd = o3d.io.read_triangle_mesh(
        armadillo_data.path).sample_points_poisson_disk(N)
    print("pcd.colors=",pcd)
    o3d.web_visualizer.draw([pcd])

    # Fit to unit cube.
    pcd.scale(1 / np.max(pcd.get_max_bound() - pcd.get_min_bound()),
              center=pcd.get_center())
    print("pcd.colors=",pcd)
    o3d.web_visualizer.draw([pcd])

    pcd.colors = o3d.utility.Vector3dVector(np.random.uniform(0, 1,
                                                              size=(N, 3)))
    print("pcd.colors=",pcd)
    print('Displaying input point cloud ...')
    #o3d.visualization.draw([pcd])
    o3d.web_visualizer.draw([pcd])
    
    print('Displaying voxel grid ...')
    voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(pcd,
                                                                voxel_size=0.05)
    #o3d.visualization.draw([voxel_grid])
    o3d.web_visualizer.draw([voxel_grid])

pcd.colors= PointCloud with 2000 points.


WebVisualizer(window_uid='window_13')

pcd.colors= PointCloud with 2000 points.


WebVisualizer(window_uid='window_14')

pcd.colors= PointCloud with 2000 points.
Displaying input point cloud ...


WebVisualizer(window_uid='window_15')

Displaying voxel grid ...


WebVisualizer(window_uid='window_16')

In [ ]:
import open3d as o3d
import numpy as np
import open3d as o3d

N = 2000

if __name__ == "__main__":
    print("Load a ply point cloud, print it, and render it")
    sample_ply_data = o3d.data.PLYPointCloud()
    pcd = o3d.io.read_point_cloud(sample_ply_data.path)
    # Flip it, otherwise the pointcloud will be upside down.
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    print(pcd)
    #o3d.visualization.draw([pcd])
    print("Downsample the point cloud with a voxel of 0.05")
    downpcd = pcd.voxel_down_sample(voxel_size=0.05)
    #o3d.visualization.draw([downpcd])

    #pcd.scale(1 / np.max(pcd.get_max_bound() - pcd.get_min_bound()),
     #         center=pcd.get_center())
    #pcd.colors = o3d.utility.Vector3dVector(np.random.uniform(0, 1,
     #                                                         size=(N, 3)))
    print('Displaying input point cloud ...')
    #o3d.visualization.draw([pcd])
    #o3d.web_visualizer.draw([pcd])
    
    print('Displaying voxel grid ...')
    voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(downpcd,
                                                                voxel_size=0.05)
    #o3d.visualization.draw([voxel_grid])
    o3d.web_visualizer.draw([voxel_grid])

Load a ply point cloud, print it, and render it
PointCloud with 196133 points.
Downsample the point cloud with a voxel of 0.05
Displaying input point cloud ...
Displaying voxel grid ...


WebVisualizer(window_uid='window_17')

### Segmentation d'Open3d : 
Open3D-master\examples\python\geometry\point_cloud_plane_segmentation.py

In [ ]:
import open3d as o3d

if __name__ == "__main__":

    sample_pcd_data = o3d.data.EaglePointCloud()
    pcd = o3d.io.read_point_cloud(sample_pcd_data.path)
    # Flip it, otherwise the pointcloud will be upside down.
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    plane_model, inliers = pcd.segment_plane(distance_threshold=0.01,
                                             ransac_n=3,
                                             num_iterations=1000)
    [a, b, c, d] = plane_model
    print(f"Plane equation: {a:.2f}x + {b:.2f}y + {c:.2f}z + {d:.2f} = 0")
    print("Displaying pointcloud with planar points in red ...")
    inlier_cloud = pcd.select_by_index(inliers)
    inlier_cloud.paint_uniform_color([1.0, 0, 0])
    outlier_cloud = pcd.select_by_index(inliers, invert=True)
    #o3d.visualization.draw([inlier_cloud, outlier_cloud])
    o3d.web_visualizer.draw([inlier_cloud, outlier_cloud])    

Plane equation: 0.94x + 0.20y + -0.29z + -2.77 = 0
Displaying pointcloud with planar points in red ...


WebVisualizer(window_uid='window_1')

# Affichage de dataset 

In [ ]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt
from open3d.web_visualizer import draw

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[Open3D INFO] Resetting default logger to print to terminal.


In [ ]:
path1 = "./Data/beam_1.txt"
path2 = "./Data/auditorium_1.txt"
path_df3_xyz = "C:/Users/Utilisateur/Documents/1_BDD_ISEN/PointCleanNet_data/pointCleanNetDataset/"

In [ ]:
#sample_ply_data = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(path1, format='xyzrgb')
#o3d.web_visualizer.draw([pcd])
# ou avec draw
draw([pcd])

WebVisualizer(window_uid='window_19')

 - **pour importer ses fichier**</br>
 pcd = o3d.io.read_point_cloud(path, format='xyzrgb')</br>
 http://www.open3d.org/docs/latest/tutorial/Basic/file_io.html

### Affichage avec Tensorbord

conda install -c conda-forge --name py38 tensorboard -y </br>
*c:\Users\Utilisateur\.vscode\extensions\ms-python.python-2022.10.1\pythonFiles\shell_exec.py conda install -c conda-forge --name py38 tensorboard -y C:/Users/UTILIS~1/AppData/Local/Temp/tmp-8356ZtmzbbQwiaaJ.log </br>
*Executing command in shell >> conda install -c conda-forge --name py38 tensorboard -y

**=> Faut cuda !!**

In [ ]:
!pip install -U -q open3d

     |████████████████████████████████| 408.6 MB 22 kB/s 
     |████████████████████████████████| 596 kB 50.4 MB/s 
     |████████████████████████████████| 8.8 MB 43.0 MB/s 
     |████████████████████████████████| 3.1 MB 49.5 MB/s 
     |████████████████████████████████| 1.1 MB 51.6 MB/s 
     |████████████████████████████████| 54 kB 2.2 MB/s 
     |████████████████████████████████| 9.7 MB 39.8 MB/s 
     |████████████████████████████████| 423 kB 42.3 MB/s 
     |████████████████████████████████| 344 kB 63.8 MB/s 
     |████████████████████████████████| 1.6 MB 39.1 MB/s 
     |████████████████████████████████| 1.2 MB 52.6 MB/s 
     |████████████████████████████████| 563 kB 54.5 MB/s 
     |████████████████████████████████| 80 kB 7.0 MB/s 
     |████████████████████████████████| 54 kB 2.3 MB/s 
     |████████████████████████████████| 59 kB 6.2 MB/s 
     |████████████████████████████████| 133 kB 37.1 MB/s 
     |████████████████████████████████| 71 kB 169 kB/s 
     |██████████████████

In [ ]:
!python -c "import open3d as o3d; print(o3d.__version__)"

0.15.2


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import sys    
path_to_module = '/content/drive/MyDrive/dataset/'
sys.path.append(path_to_module)

In [ ]:
# Select you GPU
I_GPU = 0
import torch
torch.cuda.set_device(I_GPU)

In [ ]:
import open3d as o3d
# Monkey-patch torch.utils.tensorboard.SummaryWriter

In [ ]:
import open3d as o3d
# Monkey-patch torch.utils.tensorboard.SummaryWriter
from open3d.visualization.tensorboard_plugin import summary
# Utility function to convert Open3D geometry to a dictionary format
from open3d.visualization.tensorboard_plugin.util import to_dict_batch
from torch.utils.tensorboard import SummaryWrite

ImportError: ignored

In [ ]:
import open3d as o3d
# Monkey-patch torch.utils.tensorboard.SummaryWriter
from open3d.visualization.tensorboard_plugin import summary
# Utility function to convert Open3D geometry to a dictionary format
from open3d.visualization.tensorboard_plugin.util import to_dict_batch
from torch.utils.tensorboard import SummaryWriter

cube = o3d.geometry.TriangleMesh.create_box(1, 2, 4)
cube.compute_vertex_normals()
cylinder = o3d.geometry.TriangleMesh.create_cylinder(radius=1.0,
                                                     height=2.0,
                                                     resolution=20,
                                                     split=4)
cylinder.compute_vertex_normals()
colors = [(1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)]

In [ ]:
#pip install --upgrade h5py
import open3d as o3d
from open3d.visualization.tensorboard_plugin import summary
# Utility function to convert Open3D geometry to a dictionary format
from open3d.visualization.tensorboard_plugin.util import to_dict_batch
import tensorflow as tf
# ... geometry creation code as above ...
logdir = "demo_logs/tf/small_scale"
writer = tf.summary.create_file_writer(logdir)
with writer.as_default():
    for step in range(3):
        cube.paint_uniform_color(colors[step])
        summary.add_3d('cube', to_dict_batch([cube]), step=step, logdir=logdir)
        cylinder.paint_uniform_color(colors[step])
        summary.add_3d('cylinder', to_dict_batch([cylinder]), step=step,
                       logdir=logdir)

### Transformation 
**(translate, rotate, scaleet transform)**</br>
http://www.open3d.org/docs/latest/tutorial/Basic/transformation.html

In [ ]:
import copy
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
T = np.eye(4)
print(T)
T[:3, :3] = mesh.get_rotation_matrix_from_xyz((0, np.pi / 3, np.pi / 2))
print(T)
T[0, 3] = 1
T[1, 3] = 1.3
T[2, 3] = -1.3
print(T)
mesh_t = copy.deepcopy(mesh).transform(T)
#o3d.visualization.draw_geometries([mesh, mesh_t])
o3d.web_visualizer.draw([mesh, mesh_t])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 3.06161700e-17 -5.00000000e-01  8.66025404e-01  0.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00  0.00000000e+00]
 [-5.30287619e-17  8.66025404e-01  5.00000000e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 3.06161700e-17 -5.00000000e-01  8.66025404e-01  1.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00  1.30000000e+00]
 [-5.30287619e-17  8.66025404e-01  5.00000000e-01 -1.30000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


WebVisualizer(window_uid='window_23')

### Clustering puis Segmentation avec un fichier \*.txt (xyzrgb)

In [ ]:
path = "C:/Users/Utilisateur/Documents/1_BDD_ISEN/S3DIS/hallway_1/hallway_1.txt"

if __name__ == "__main__":
    sample_ply_data = o3d.data.PLYPointCloud()
    pcd = o3d.io.read_point_cloud(path, format='xyzrgb')
    #o3d.web_visualizer.draw([pcd])
    # Flip it, otherwise the pointcloud will be upside down.
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])

    with o3d.utility.VerbosityContextManager(
            o3d.utility.VerbosityLevel.Debug) as cm:
        labels = np.array(
            pcd.cluster_dbscan(eps=0.02, min_points=10, print_progress=True))

    max_label = labels.max()
    print(f"point cloud has {max_label + 1} clusters")
    colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
    colors[labels < 0] = 0
    pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])
    #o3d.visualization.draw([pcd])
    #draw([pcd]) #sol 1 
    o3d.web_visualizer.draw([pcd])

point cloud has 38 clusters


WebVisualizer(window_uid='window_2')

In [ ]:
path = "C:/Users/Utilisateur/Documents/1_BDD_ISEN/S3DIS/hallway_1/hallway_1.txt"

if __name__ == "__main__":

    #sample_pcd_data = o3d.data.EaglePointCloud()
    #pcd = o3d.io.read_point_cloud(sample_pcd_data.path)
    pcd = o3d.io.read_point_cloud(path, format='xyzrgb')
    # Flip it, otherwise the pointcloud will be upside down.
    pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
    plane_model, inliers = pcd.segment_plane(distance_threshold=0.01,
                                             ransac_n=3,
                                             num_iterations=1000)
    [a, b, c, d] = plane_model
    print(f"Plane equation: {a:.2f}x + {b:.2f}y + {c:.2f}z + {d:.2f} = 0")
    print("Displaying pointcloud with planar points in red ...")
    inlier_cloud = pcd.select_by_index(inliers)
    inlier_cloud.paint_uniform_color([1.0, 0, 0])
    outlier_cloud = pcd.select_by_index(inliers, invert=True)
    #o3d.visualization.draw([inlier_cloud, outlier_cloud])
    o3d.web_visualizer.draw([inlier_cloud, outlier_cloud])

Plane equation: -0.00x + -0.01y + 1.00z + 2.67 = 0
Displaying pointcloud with planar points in red ...


WebVisualizer(window_uid='window_3')